### ISSUE TITLE
File missing /usr/lib/unifi/data/firmware/firmware_meta.json

### ISSUE THREAD

**Issue by gritstub** [linuxserver/docker-unifi-controller#121]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

No error

## Current Behavior

```
[2022-01-19T05:23:53,707] <inform-3> ERROR system - Failed to load file[/usr/lib/unifi/data/firmware/firmware_meta.json] as JSON
java.io.FileNotFoundException: /usr/lib/unifi/data/firmware/firmware_meta.json (No such file or directory)
        at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_312]
        at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_312]
        at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_312]
        at java.io.FileInputStream.<init>(FileInputStream.java:93) ~[?:1.8.0_312]
        at java.io.FileReader.<init>(FileReader.java:58) ~[?:1.8.0_312]
        at com.ubnt.data.X.loadJSON(Unknown Source) ~[ace.jar:?]
        at com.ubnt.service.system.returnObject.o00000(Unknown Source) ~[ace.jar:?]
        at com.ubnt.service.firmware.L.classclass(Unknown Source) ~[ace.jar:?]
        at com.ubnt.service.firmware.L.öÖ0000(Unknown Source) ~[ace.jar:?]
        at com.ubnt.service.firmware.L.public(Unknown Source) ~[ace.jar:?]
        at com.ubnt.service.firmware.L.Õ00000(Unknown Source) ~[ace.jar:?]
        at com.ubnt.service.devmgr.VA.publicnew(Unknown Source) ~[ace.jar:?]
        at com.ubnt.service.devmgr.inform.A.o00000(Unknown Source) ~[ace.jar:?]
        at com.ubnt.service.devmgr.inform.A.o00000(Unknown Source) ~[ace.jar:?]
        at com.ubnt.service.devmgr.inform.A.Ò00000(Unknown Source) ~[ace.jar:?]
        at com.ubnt.service.lock.OoOO.o00000(Unknown Source) [ace.jar:?]
        at com.ubnt.service.lock.F.new(Unknown Source) [ace.jar:?]
        at com.ubnt.service.lock.F.o00000(Unknown Source) [ace.jar:?]
        at com.ubnt.service.devmgr.H.o00000(Unknown Source) [ace.jar:?]
        at com.ubnt.service.devmgr.inform.A.Ò00000(Unknown Source) [ace.jar:?]
        at com.ubnt.service.devmgr.inform.A.o00000(Unknown Source) [ace.jar:?]
        at com.ubnt.net.InformServlet.o00000(Unknown Source) [ace.jar:?]
        at com.ubnt.net.InformServlet.service(Unknown Source) [ace.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-embed-core-8.5.56.jar:8.5.56]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-8.5.56.jar:8.5.56]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.56.jar:8.5.56]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.5.56.jar:8.5.56]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.56.jar:8.5.56]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.56.jar:8.5.56]
        at com.ubnt.ace.view.UbiosHttpsFilter.doFilter(Unknown Source) [ace.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.56.jar:8.5.56]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.56.jar:8.5.56]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [tomcat-embed-core-8.5.56.jar:8.5.56]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.56.jar:8.5.56]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543) [tomcat-embed-core-8.5.56.jar:8.5.56]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-8.5.56.jar:8.5.56]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.56.jar:8.5.56]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.56.jar:8.5.56]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-8.5.56.jar:8.5.56]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615) [tomcat-embed-core-8.5.56.jar:8.5.56]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-8.5.56.jar:8.5.56]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818) [tomcat-embed-core-8.5.56.jar:8.5.56]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1627) [tomcat-embed-core-8.5.56.jar:8.5.56]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.56.jar:8.5.56]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_312]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_312]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.56.jar:8.5.56]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
```

## Steps to Reproduce

1. Adopt an AP, following instructions for "set inform"

## Environment
**OS:** Linux Host
**CPU architecture:** x86_64
**How docker service was installed:**

https://hub.docker.com/r/linuxserver/unifi-controller

**Comment by gritstub** [comment]
There was a file on my system ```/usr/lib/unifi/data/firmware.json```

**Comment by gilsdorfer** [comment]
Yep, same issue here.

**Comment by wizu** [comment]
Same problem. Can we fix it?

**Comment by fermulator** [comment]
same issue here (remove bot)

**Comment by aaron-axisa** [comment]
same here

**Comment by drizuid** [comment]
The OP didn't provide the docker compose or docker run used, they didn't provide info on how the docker service was installed, full docker logs weren't provided. Unless someone is willing to make the effort and provide the info that is requested, there is nothing for us to do.

**Comment by jasonmp85** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

This bot should be printed into a 3D form that can feel pain, tied to four horses pointing each of the cardinal directions, and rent asunder.

Surprise! Just because maintainers have ignored an issue long enough doesn't mean it has fixed itself!

**Comment by Roxedus** [comment]
It was not ignored, it was waiting on either a fully filled issue template, or specific reproduction steps.

**Comment by drizuid** [comment]
unfortunately, the bot is unable to fix users can't complete simple tasks, the bot also cannot cure stupid :(  One day perhaps
