### ISSUE TITLE
Fresh install, doing a backup restore causes it to time out

### ISSUE THREAD

**Issue by baldfox** [linuxserver/docker-unifi-controller#125]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

I would expect the Unifi administration page to come alive
## Current Behavior

It times out, it stays on the "it's being restored page"

## Steps to Reproduce

1. run the stack, wait for setup window
2. select backup file
3. wait for the restoration

## Environment
**OS:**
**CPU architecture:** x86_64
**How docker service was installed:**
Via Portainer running on Ubuntu 21.04

## Command used to create docker container (run/create/compose/screenshot)

version: "2.1"
services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      - /docker/appdata/unifi:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8081:8080
      - 8443:8443
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: bridge

## Docker logs

Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    911
User gid:    911
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 15-install: executing... 
[cont-init.d] 15-install: exited 0.
[cont-init.d] 19-deprecate: executing... 
[cont-init.d] 19-deprecate: exited 0.
[cont-init.d] 20-config: executing... 
*** Setting Java memory limit to 1024 ***
*** Setting Java memory minimum to 1024 ***
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore /config/data/keystore -destkeystore /config/data/keystore -deststoretype pkcs12".
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
org.tuckey.web.filters.urlrewrite.UrlRewriteFilter INFO: destroy called
Exception in thread "Thread-14" java.lang.IllegalStateException: BeanFactory not initialized or already closed - call 'refresh' before accessing beans via the ApplicationContext
	at org.springframework.context.support.AbstractRefreshableApplicationContext.getBeanFactory(AbstractRefreshableApplicationContext.java:168)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1172)
	at com.ubnt.service.C.Ö00000(Unknown Source)
	at com.ubnt.ace.Launcher.Ò00000(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

**Comment by liambresnahan** [comment]
I have the same issue here. Importing from the same controller version on another install (MacOS based) and see a similar issue:

```2022-05-02T21:10:26.919525862Z -------------------------------------
2022-05-02T21:10:26.919529072Z           _         ()
2022-05-02T21:10:26.919531598Z          | |  ___   _    __
2022-05-02T21:10:26.919533987Z          | | / __| | |  /  \
2022-05-02T21:10:26.919536509Z          | | \__ \ | | | () |
2022-05-02T21:10:26.919539079Z          |_| |___/ |_|  \__/
2022-05-02T21:10:26.919541609Z 
2022-05-02T21:10:26.919543971Z 
2022-05-02T21:10:26.919546609Z Brought to you by linuxserver.io
2022-05-02T21:10:26.919549109Z -------------------------------------
2022-05-02T21:10:26.919551422Z 
2022-05-02T21:10:26.919553754Z To support LSIO projects visit:
2022-05-02T21:10:26.919556085Z https://www.linuxserver.io/donate/
2022-05-02T21:10:26.919558441Z -------------------------------------
2022-05-02T21:10:26.919560758Z GID/UID
2022-05-02T21:10:26.919563113Z -------------------------------------
2022-05-02T21:10:26.921655801Z 
2022-05-02T21:10:26.921665795Z User uid:    1000
2022-05-02T21:10:26.921668997Z User gid:    1000
2022-05-02T21:10:26.921671549Z -------------------------------------
2022-05-02T21:10:26.921674064Z 
2022-05-02T21:10:26.925113645Z [cont-init.d] 10-adduser: exited 0.
2022-05-02T21:10:26.925851639Z [cont-init.d] 15-install: executing... 
2022-05-02T21:10:26.928112974Z *** installing unifi packages ***
2022-05-02T21:10:26.950881685Z Selecting previously unselected package unifi.
2022-05-02T21:10:26.956189532Z (Reading database ... 8893 files and directories currently installed.)
2022-05-02T21:10:26.956441285Z Preparing to unpack /app/unifi.deb ...
2022-05-02T21:10:27.022810241Z Unpacking unifi (7.1.61-17860-1) ...
2022-05-02T21:10:36.314188094Z Setting up unifi (7.1.61-17860-1) ...
2022-05-02T21:10:36.495987474Z invoke-rc.d: could not determine current runlevel
2022-05-02T21:10:36.498199206Z invoke-rc.d: policy-rc.d denied execution of start.
2022-05-02T21:10:36.510273077Z [cont-init.d] 15-install: exited 0.
2022-05-02T21:10:36.511140718Z [cont-init.d] 19-deprecate: executing... 
2022-05-02T21:10:36.514431322Z [cont-init.d] 19-deprecate: exited 0.
2022-05-02T21:10:36.515135833Z [cont-init.d] 20-config: executing... 
2022-05-02T21:10:36.526097375Z *** Setting Java memory limit to 1024 ***
2022-05-02T21:10:36.526114939Z *** Setting Java memory minimum to 1024 ***
2022-05-02T21:10:36.559344159Z [cont-init.d] 20-config: exited 0.
2022-05-02T21:10:36.560055589Z [cont-init.d] 30-keygen: executing... 
2022-05-02T21:10:37.070919410Z 
2022-05-02T21:10:37.070946938Z Warning:
2022-05-02T21:10:37.071388768Z The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore /config/data/keystore -destkeystore /config/data/keystore -deststoretype pkcs12".
2022-05-02T21:10:37.092838757Z [cont-init.d] 30-keygen: exited 0.
2022-05-02T21:10:37.093527852Z [cont-init.d] 90-custom-folders: executing... 
2022-05-02T21:10:37.097792247Z [cont-init.d] 90-custom-folders: exited 0.
2022-05-02T21:10:37.098515521Z [cont-init.d] 99-custom-scripts: executing... 
2022-05-02T21:10:37.105171743Z [custom-init] no custom files found exiting...
2022-05-02T21:10:37.105491925Z [cont-init.d] 99-custom-scripts: exited 0.
2022-05-02T21:10:37.105933331Z [cont-init.d] done.
2022-05-02T21:10:37.106369336Z [services.d] starting services
2022-05-02T21:10:37.109614359Z [services.d] done.
2022-05-02T21:10:59.006145312Z org.tuckey.web.filters.urlrewrite.UrlRewriteFilter INFO: destroy called
2022-05-02T21:11:02.139866653Z Exception in thread "Thread-11" java.lang.IllegalStateException: BeanFactory not initialized or already closed - call 'refresh' before accessing beans via the ApplicationContext
2022-05-02T21:11:02.139891169Z 	at org.springframework.context.support.AbstractRefreshableApplicationContext.getBeanFactory(AbstractRefreshableApplicationContext.java:168)
2022-05-02T21:11:02.139896242Z 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1172)
2022-05-02T21:11:02.139900548Z 	at com.ubnt.service.ooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.return(Unknown Source)
2022-05-02T21:11:02.139910789Z 	at com.ubnt.ace.Launcher.o00000(Unknown Source)
2022-05-02T21:11:02.139914074Z 	at java.lang.Thread.run(Thread.java:748)```

**Comment by j0nnymoe** [comment]
I suspect the issue here is either permissions or backups from bare metal installs crash the container when they're restored.

**Comment by ranasats** [comment]
Having the same issues, logs look identical.
