### ISSUE TITLE
Exception in thread "launcher" java.lang.NullPointerException: Web context failed to initialize - Web 404

### ISSUE THREAD

**Issue by b-reich** [linuxserver/docker-unifi-controller#132]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Unifi Controller is reachable over https port8443

## Current Behavior

Webinterface got just a 404
![image](https://user-images.githubusercontent.com/1573025/158805911-63ec9859-5394-4ccc-b0d0-3cee7e0b6a70.png)

## Steps to Reproduce
1. pull the latest container
2. restart the container

## Environment
**OS:** debian 11
**CPU architecture:** x86_64/
**How docker service was installed:** docker ce repo

## Command used to create docker container (run/create/compose/screenshot)

```yaml 
---
version: "2"
services:
  unifi-controller:
    image: linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024M #optional
    volumes:
      - ./data:/config
    network_mode: host
#    ports:
#      - 3478:3478/udp
#      - 10001:10001/udp
#      - 8080:8080
#      - 8081:8081
#      - 8443:8443
#      - 8843:8843
#      - 8880:8880
#      - 6789:6789
    restart: unless-stopped
```

## Docker logs

```
docker-compose logs -f
Attaching to unifi-controller
unifi-controller    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
unifi-controller    | [s6-init] ensuring user provided files have correct perms...exited 0.
unifi-controller    | [fix-attrs.d] applying ownership & permissions fixes...
unifi-controller    | [fix-attrs.d] done.
unifi-controller    | [cont-init.d] executing container initialization scripts...
unifi-controller    | [cont-init.d] 01-envfile: executing... 
unifi-controller    | [cont-init.d] 01-envfile: exited 0.
unifi-controller    | [cont-init.d] 01-migrations: executing... 
unifi-controller    | [migrations] started
unifi-controller    | [migrations] no migrations found
unifi-controller    | [cont-init.d] 01-migrations: exited 0.
unifi-controller    | [cont-init.d] 02-tamper-check: executing... 
unifi-controller    | [cont-init.d] 02-tamper-check: exited 0.
unifi-controller    | [cont-init.d] 10-adduser: executing... 
unifi-controller    | 
unifi-controller    | -------------------------------------
unifi-controller    |           _         ()
unifi-controller    |          | |  ___   _    __
unifi-controller    |          | | / __| | |  /  \
unifi-controller    |          | | \__ \ | | | () |
unifi-controller    |          |_| |___/ |_|  \__/
unifi-controller    | 
unifi-controller    | 
unifi-controller    | Brought to you by linuxserver.io
unifi-controller    | -------------------------------------
unifi-controller    | 
unifi-controller    | To support LSIO projects visit:
unifi-controller    | https://www.linuxserver.io/donate/
unifi-controller    | -------------------------------------
unifi-controller    | GID/UID
unifi-controller    | -------------------------------------
unifi-controller    | 
unifi-controller    | User uid:    1000
unifi-controller    | User gid:    1000
unifi-controller    | -------------------------------------
unifi-controller    | 
unifi-controller    | [cont-init.d] 10-adduser: exited 0.
unifi-controller    | [cont-init.d] 15-install: executing... 
unifi-controller    | *** installing unifi packages ***
unifi-controller    | Selecting previously unselected package unifi.
unifi-controller    | (Reading database ... 8893 files and directories currently installed.)
unifi-controller    | Preparing to unpack /app/unifi.deb ...
unifi-controller    | Unpacking unifi (7.0.23-17288-1) ...
unifi-controller    | Setting up unifi (7.0.23-17288-1) ...
unifi-controller    | invoke-rc.d: could not determine current runlevel
unifi-controller    | invoke-rc.d: policy-rc.d denied execution of start.
unifi-controller    | [cont-init.d] 15-install: exited 0.
unifi-controller    | [cont-init.d] 19-deprecate: executing... 
unifi-controller    | [cont-init.d] 19-deprecate: exited 0.
unifi-controller    | [cont-init.d] 20-config: executing... 
unifi-controller    | *** Setting Java memory limit to 1024M ***
unifi-controller    | [cont-init.d] 20-config: exited 0.
unifi-controller    | [cont-init.d] 30-keygen: executing... 
unifi-controller    | [cont-init.d] 30-keygen: exited 0.
unifi-controller    | [cont-init.d] 90-custom-folders: executing... 
unifi-controller    | [cont-init.d] 90-custom-folders: exited 0.
unifi-controller    | [cont-init.d] 99-custom-scripts: executing... 
unifi-controller    | [custom-init] no custom files found exiting...
unifi-controller    | [cont-init.d] 99-custom-scripts: exited 0.
unifi-controller    | [cont-init.d] done.
unifi-controller    | [services.d] starting services
unifi-controller    | [services.d] done.
unifi-controller    | Exception in thread "launcher" java.lang.NullPointerException: Web context failed to initialize
unifi-controller    | 	at java.util.Objects.requireNonNull(Objects.java:228)
unifi-controller    | 	at com.ubnt.net.B.ÖO0000(Unknown Source)
unifi-controller    | 	at com.ubnt.net.B.Ø00000(Unknown Source)
unifi-controller    | 	at com.ubnt.service.Object.ÕÔ0000(Unknown Source)
unifi-controller    | 	at com.ubnt.ace.Launcher.main(Unknown Source)
unifi-controller    | [cont-finish.d] executing container finish scripts...
unifi-controller    | [cont-finish.d] done.
unifi-controller    | [s6-finish] waiting for services.
unifi-controller    | [s6-finish] sending all processes the TERM signal.
unifi-controller    | [s6-finish] sending all processes the KILL signal and exiting.
unifi-controller    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
unifi-controller    | [s6-init] ensuring user provided files have correct perms...exited 0.
unifi-controller    | [fix-attrs.d] applying ownership & permissions fixes...
unifi-controller    | [fix-attrs.d] done.
unifi-controller    | [cont-init.d] executing container initialization scripts...
unifi-controller    | [cont-init.d] 01-envfile: executing... 
unifi-controller    | [cont-init.d] 01-envfile: exited 0.
unifi-controller    | [cont-init.d] 01-migrations: executing... 
unifi-controller    | [migrations] started
unifi-controller    | [migrations] no migrations found
unifi-controller    | [cont-init.d] 01-migrations: exited 0.
unifi-controller    | [cont-init.d] 02-tamper-check: executing... 
unifi-controller    | [cont-init.d] 02-tamper-check: exited 0.
unifi-controller    | [cont-init.d] 10-adduser: executing... 
unifi-controller    | usermod: no changes
unifi-controller    | 
unifi-controller    | -------------------------------------
unifi-controller    |           _         ()
unifi-controller    |          | |  ___   _    __
unifi-controller    |          | | / __| | |  /  \
unifi-controller    |          | | \__ \ | | | () |
unifi-controller    |          |_| |___/ |_|  \__/
unifi-controller    | 
unifi-controller    | 
unifi-controller    | Brought to you by linuxserver.io
unifi-controller    | -------------------------------------
unifi-controller    | 
unifi-controller    | To support LSIO projects visit:
unifi-controller    | https://www.linuxserver.io/donate/
unifi-controller    | -------------------------------------
unifi-controller    | GID/UID
unifi-controller    | -------------------------------------
unifi-controller    | 
unifi-controller    | User uid:    1000
unifi-controller    | User gid:    1000
unifi-controller    | -------------------------------------
unifi-controller    | 
unifi-controller    | [cont-init.d] 10-adduser: exited 0.
unifi-controller    | [cont-init.d] 15-install: executing... 
unifi-controller    | [cont-init.d] 15-install: exited 0.
unifi-controller    | [cont-init.d] 19-deprecate: executing... 
unifi-controller    | [cont-init.d] 19-deprecate: exited 0.
unifi-controller    | [cont-init.d] 20-config: executing... 
unifi-controller    | *** Setting Java memory limit to 1024M ***
unifi-controller    | [cont-init.d] 20-config: exited 0.
unifi-controller    | [cont-init.d] 30-keygen: executing... 
unifi-controller    | [cont-init.d] 30-keygen: exited 0.
unifi-controller    | [cont-init.d] 90-custom-folders: executing... 
unifi-controller    | [cont-init.d] 90-custom-folders: exited 0.
unifi-controller    | [cont-init.d] 99-custom-scripts: executing... 
unifi-controller    | [custom-init] no custom files found exiting...
unifi-controller    | [cont-init.d] 99-custom-scripts: exited 0.
unifi-controller    | [cont-init.d] done.
unifi-controller    | [services.d] starting services
unifi-controller    | [services.d] done.
unifi-controller    | Exception in thread "launcher" java.lang.NullPointerException: Web context failed to initialize
unifi-controller    | 	at java.util.Objects.requireNonNull(Objects.java:228)
unifi-controller    | 	at com.ubnt.net.B.ÖO0000(Unknown Source)
unifi-controller    | 	at com.ubnt.net.B.Ø00000(Unknown Source)
unifi-controller    | 	at com.ubnt.service.Object.ÕÔ0000(Unknown Source)
unifi-controller    | 	at com.ubnt.ace.Launcher.main(Unknown Source)
```

**Comment by j0nnymoe** [comment]
The 404 errors have been discussed a lot in our issues and it's due to slow startup of the unifi controller, not our container.
