### ISSUE TITLE
[BUG] The new image dies after a few minutes

### ISSUE THREAD

**Issue by jfreimuth** [linuxserver/docker-unifi-controller#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After updating the image from 7.2.95 to the new version 7.3.76 UniFi controller the container dies after a couple of minutes.
The controller logs a lot of 

java.lang.NullPointerException:

### Steps To Reproduce

docker run -d \
  --name=unifi-controller \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/Berlin \
  -e MEM_LIMIT=1024 \
  -e MEM_STARTUP=1024 \
  -p 8443:8443 \
  -p 3478:3478/udp \
  -p 10001:10001/udp \
  -p 8080:8080 \
  -p 1900:1900/udp \
  -p 8843:8843 \
  -p 8880:8880 \
  -p 6789:6789 \
  -p 5514:5514/udp \
  -v /var/lib/unifi/config:/config \
  -v /var/lib/unifi/data:/data \
  --restart unless-stopped \
  lscr.io/linuxserver/unifi-controller:7.3.76

### Environment

```markdown
- OS: 
Debian GNU/Linux 11 (Linux raspberrypi 5.15.74-v8+ #1595 SMP PREEMPT Wed Oct 26 11:07:24 BST 2022 aarch64 GNU/Linux)

- How docker service was installed:
apt-cache policy docker-ce                                                                                                                                                                               10:50:36 
docker-ce:
  Installiert:           5:20.10.21~3-0~debian-bullseye
  Installationskandidat: 5:20.10.21~3-0~debian-bullseye
  Versionstabelle:
 *** 5:20.10.21~3-0~debian-bullseye 500
        500 https://download.docker.com/linux/debian bullseye/stable arm64 Packages
        100 /var/lib/dpkg/status
```

### CPU architecture

arm64

### Docker creation

```bash
docker run -d \
  --name=unifi-controller \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/Berlin \
  -e MEM_LIMIT=1024 \
  -e MEM_STARTUP=1024 \
  -p 8443:8443 \
  -p 3478:3478/udp \
  -p 10001:10001/udp \
  -p 8080:8080 \
  -p 1900:1900/udp \
  -p 8843:8843 \
  -p 8880:8880 \
  -p 6789:6789 \
  -p 5514:5514/udp \
  -v /var/lib/unifi/config:/config \
  -v /var/lib/unifi/data:/data \
  --restart unless-stopped \
  lscr.io/linuxserver/unifi-controller:7.3.76
```

### Container logs

```bash
[2022-12-08T21:10:58,804] <launcher> INFO  system - Tomcat startup took 4532ms
[2022-12-08T21:10:58,811] <launcher> INFO  db     - Version 7.3.76 has not changed, skipping migration
[2022-12-08T21:10:58,881] <launcher> INFO  tomcat - Adding basic REST API support during the startup
[2022-12-08T21:11:12,805] <launcher> INFO  db     - waiting for db connection...
[2022-12-08T21:11:15,187] <db-server> INFO  db     - 2022-12-08T21:11:15.186+0100 I STORAGE  [main] Engine custom option: cache_size=256M
[2022-12-08T21:11:15,308] <launcher> INFO  db     - Connecting to mongodb://localhost:27117
[2022-12-08T21:11:19,850] <launcher> INFO  db     - setting mongodb features compatibility version to 3.6
[2022-12-08T21:11:20,489] <launcher> INFO  system - ======================================================================
[2022-12-08T21:11:20,490] <launcher> INFO  system - UniFi 7.3.76 (build atag_7.3.76_19582 - release/release) is started
[2022-12-08T21:11:20,490] <launcher> INFO  system - ======================================================================
[2022-12-08T21:11:20,499] <launcher> INFO  system - BASE dir:/usr/lib/unifi
[2022-12-08T21:11:20,703] <launcher> INFO  system - Current System IP: 172.17.0.2
[2022-12-08T21:11:20,705] <launcher> INFO  system - Hostname: 36204fc427be
[2022-12-08T21:11:20,706] <launcher> INFO  system - ubic.env: prod
[2022-12-08T21:11:37,367] <launcher> INFO  productinfo - Using controller channel=RELEASE, firmware channel=RELEASE. Available controller channels=[RELEASE], available firmware channels=[RELEASE]. SSO is enabled.
[2022-12-08T21:11:38,523] <launcher> INFO  webrtc - WebRTC library version: EvoStream Media Server (www.evostream.com) build v2.9.1 - Gladiator - (built for Debian-9.2.1-aarch64 on 2020-02-05T23:57:07.000) OpenSSL version: 1.1.1d usrsctp version: v0.1.2 compiled on machine: Linux debian-9-2-1-64 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u5 (2018-09-30) x86_64 GNU/Linux
[2022-12-08T21:11:47,079] <launcher> INFO  blebridge - maxConcurrentBridgeDiscovery = 4
[2022-12-08T21:11:52,122] <launcher> INFO  tomcat - systemd: Watchdog ping NOT enabled
[2022-12-08T21:11:52,123] <launcher> INFO  tomcat - systemd: Startup completed. Ready for watchdog keep-alive checking.
[2022-12-08T21:12:06,553] <webapi-15> ERROR [dispatcher] - Servlet.service() for servlet [dispatcher] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:889) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.cache.LocalCache.getIfPresent(LocalCache.java:3970) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.cache.LocalCache$LocalManualCache.getIfPresent(LocalCache.java:4857) ~[guava-31.0.1-jre.jar:?]
	at com.ubnt.service.system.PA.OO0000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.system.PA.Ô00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.BA.öøÖ000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.client.P.forsuper(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.client.P.new(Unknown Source) ~[ace.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at com.ubnt.service.client.P.thissuper(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.client.P.Ô00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.client.Y.Ô00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.net.v2.clients.ClientController.listClientsHistory(Unknown Source) ~[ace.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.18.jar:5.3.18]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.18.jar:5.3.18]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.18.jar:5.3.18]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.18.jar:5.3.18]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.18.jar:5.3.18]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.18.jar:5.3.18]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) ~[spring-webmvc-5.3.18.jar:5.3.18]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.18.jar:5.3.18]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.18.jar:5.3.18]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.18.jar:5.3.18]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655) ~[tomcat-embed-core-9.0.59.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.18.jar:5.3.18]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[tomcat-embed-core-9.0.59.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.59.jar:9.0.59]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.59.jar:9.0.59]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.59.jar:9.0.59]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.59.jar:9.0.59]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.59.jar:9.0.59]
	at com.ubnt.service.trace.requestmetrics.oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.doFilter(Unknown Source) ~[ace.jar:?]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354) ~[spring-web-5.3.18.jar:5.3.18]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267) ~[spring-web-5.3.18.jar:5.3.18]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.59.jar:9.0.59]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.59.jar:9.0.59]
	at com.ubnt.ace.view.AuthFilter.doFilter(Unknown Source) ~[ace.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.59.jar:9.0.59]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.59.jar:9.0.59]
	at com.ubnt.ace.view.UbiosHttpsFilter.doFilter(Unknown Source) ~[ace.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.59.jar:9.0.59]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.59.jar:9.0.59]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat-embed-core-9.0.59.jar:9.0.59]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.59.jar:9.0.59]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.59.jar:9.0.59]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat-embed-core-9.0.59.jar:9.0.59]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.59.jar:9.0.59]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.59.jar:9.0.59]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359) ~[tomcat-embed-core-9.0.59.jar:9.0.59]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat-embed-core-9.0.59.jar:9.0.59]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.59.jar:9.0.59]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889) ~[tomcat-embed-core-9.0.59.jar:9.0.59]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743) ~[tomcat-embed-core-9.0.59.jar:9.0.59]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.59.jar:9.0.59]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.59.jar:9.0.59]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.59.jar:9.0.59]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.59.jar:9.0.59]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]

[2022-12-08T22:19:46,631] <webapi-90> WARN  api    - websocket session error:Unable to unwrap data, invalid status [CLOSED]
[2022-12-08T22:20:57,382] <webapi-100> WARN  api    - websocket session error:Connection reset by peer
[2022-12-08T22:20:57,239] <webapi-93> WARN  api    - websocket session error:Connection reset by peer
[2022-12-08T22:22:08,602] <device-state-check> ERROR system - Execution failed, could not acquire lock by key[fc:ec:da:42:0c:5b] before timeout
com.ubnt.service.lock.ooOO: Failed to acquire lock before timeout
	at com.ubnt.service.lock.OoOO.Ô00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.D.Ò00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.null.while(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.null.OO0000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.null.õO0000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.int.Ø00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.classString.oO0000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.classString.Ø00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.ace.C$_OOo.run(Unknown Source) ~[ace.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
[2022-12-08T22:22:11,108] <device-state-check> WARN  monitor - Skipping check for fc:ec:da:42:0c:5b, could not acquire lock
com.ubnt.service.lock.ooOO: Failed to acquire lock before timeout
	at com.ubnt.service.lock.OoOO.Ô00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.D.Ò00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.null.while(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.null.OO0000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.null.õO0000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.int.Ø00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.classString.oO0000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.classString.Ø00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.ace.C$_OOo.run(Unknown Source) ~[ace.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
[2022-12-08T22:25:05,910] <device-state-check> ERROR system - Execution failed, could not acquire lock by key[60:22:32:3d:c9:d4] before timeout
com.ubnt.service.lock.ooOO: Failed to acquire lock before timeout
	at com.ubnt.service.lock.OoOO.Ô00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.D.Ò00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.null.while(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.null.OO0000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.null.õO0000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.int.Ø00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.classString.oO0000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.classString.Ø00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.ace.C$_OOo.run(Unknown Source) ~[ace.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
[2022-12-08T22:25:07,537] <device-state-check> WARN  monitor - Skipping check for 60:22:32:3d:c9:d4, could not acquire lock
com.ubnt.service.lock.ooOO: Failed to acquire lock before timeout
	at com.ubnt.service.lock.OoOO.Ô00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.D.Ò00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.null.while(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.null.OO0000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.null.õO0000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.int.Ø00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.classString.oO0000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.classString.Ø00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.ace.C$_OOo.run(Unknown Source) ~[ace.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
[2022-12-08T22:25:09,294] <device-state-check> ERROR system - Execution failed, could not acquire lock by key[f0:9f:c2:17:30:4f] before timeout
com.ubnt.service.lock.ooOO: Failed to acquire lock before timeout
	at com.ubnt.service.lock.OoOO.Ô00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.D.Ò00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.null.while(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.null.OO0000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.null.õO0000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.int.Ø00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.classString.oO0000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.classString.Ø00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.ace.C$_OOo.run(Unknown Source) ~[ace.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
[2022-12-08T22:25:10,698] <device-state-check> WARN  monitor - Skipping check for f0:9f:c2:17:30:4f, could not acquire lock
com.ubnt.service.lock.ooOO: Failed to acquire lock before timeout
	at com.ubnt.service.lock.OoOO.Ô00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.D.Ò00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.null.while(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.null.OO0000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.null.õO0000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.int.Ø00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.classString.oO0000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.classString.Ø00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.ace.C$_OOo.run(Unknown Source) ~[ace.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
[2022-12-08T22:26:42,084] <inform_stat-1> ERROR dev    - Error in DeviceManager.processStat()
com.mongodb.BulkWriteException: Bulk write operation error on server localhost:27117. Write errors: [BulkWriteError{index=0, code=11000, message='E11000 duplicate key error collection: ace_stat.stat_dpi index: _id_ dup key: { : ObjectId('6392568046e0fb008269a2f2') }', details={ }}, BulkWriteError{index=1, code=11000, message='E11000 duplicate key error collection: ace_stat.stat_dpi index: _id_ dup key: { : ObjectId('6392568046e0fb008269a2f3') }', details={ }}]. 
	at com.mongodb.BulkWriteHelper.translateBulkWriteException(BulkWriteHelper.java:56) ~[mongo-java-driver-3.4.3.jar:?]
	at com.mongodb.DBCollection.executeBulkWriteOperation(DBCollection.java:2313) ~[mongo-java-driver-3.4.3.jar:?]
	at com.mongodb.DBCollection.executeBulkWriteOperation(DBCollection.java:2302) ~[mongo-java-driver-3.4.3.jar:?]
	at com.mongodb.BulkWriteOperation.execute(BulkWriteOperation.java:121) ~[mongo-java-driver-3.4.3.jar:?]
	at com.ubnt.service.system.oOoo.ÓO0000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.Oo00.õØô000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.Oo00.Òöô000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.Oo00.Óõô000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.Oo00.õôô000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.r.Õ00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.r.o00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.null.ôO0000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.D.Ò00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.null.while(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.null.oO0000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.r.ø00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.TA.ÓÓÒ000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.oO00$_o.run(Unknown Source) ~[ace.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

**Comment by j0nnymoe** [comment]
Looks like permissions to me. Try using your home dir `/home/username/unifi/`.

**Comment by jfreimuth** [comment]
the 7.2.95 version works without any problems in the same environment

**Comment by jfreimuth** [comment]
I have now started with a fresh 7.3.76 installation. This works for now without problems. After restoring the backup of the 7.2.95 version, the loadAverge of my raspberry increases extremely. The java process starts to swap and the raspberry does not react anymore (only a restart helps). I start the container with the settings

 -e MEM_LIMIT=1024
  -e MEM_STARTUP=1024 

my raspberry has 2GB RAM. Is there any recommendation for the memory settings?

**Comment by jfreimuth** [comment]
Hi,

with the MEM_LIMITS reduced to 512M the network controller runs without problems
