### ISSUE TITLE
[BUG] Cannot Use Google SMTP Server as Mail Server?

### ISSUE THREAD

**Issue by ForsakenRei** [linuxserver/docker-unifi-controller#204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Failed to send test email and I didn't receive any email when I have device offline. The error message is
> There was an error sending the test email to xxx@gmail.com. Email failed to send. Please confirm your SMTP settings and try again.

It seems UDM-Pro can use Google SMTP just without issue. And the same SMTP settings works fine for my TrueNAS-Scale and UPS. So I want to see if there is anything wrong with my setup.

### Expected Behavior

I should receive an email like this:
You have received a message generated by UniFi Network

Your SMTP Server settings appear to be working correctly!

UniFi Network URL: https://unifi.xx.yy:8443/manage

### Steps To Reproduce

In the web interface, go to system -> advanced

Email Services: Custom Server
SSL: [X]
SMTP Server: smtp.gmail.com
Port: 465
Authentication: [X]
SMTP Username: <my.email>@gmail.com
SMTP Password: <my.app.password>
Sender Address: [X]
Sender Email: <my.email>@gmail.com

or 

Email Services: Custom Server
SSL: [ ]
SMTP Server: smtp.gmail.com
Port: 587
Authentication: [X]
SMTP Username: <my.email>@gmail.com
SMTP Password: <my.app.password>
Sender Address: [X]
Sender Email: <my.email>@gmail.com

Click save then put a test email address to send a test email it will fail. Web interface will ask you to confirm SMTP settings and try again, mobile app will show unknow error instead.

### Environment

```markdown
- OS:Manjaro 23.02
- RPi 4B
- How docker service was installed:pacman
```

### CPU architecture

arm64

### Docker creation

```bash
---
version: "2.1"
services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller:latest
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      - /path/to/data:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped
```

### Container logs

```bash
Docker logs from Portainer:


WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
*** Setting Java memory limit to 1024 ***
*** Setting Java memory minimum to 1024 ***
[custom-init] No custom files found, skipping...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/usr/lib/unifi/lib/tomcat-embed-core-9.0.59.jar) to field java.io.ObjectStreamClass$Caches.localDescs
WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[ls.io-init] done.
org.tuckey.web.filters.urlrewrite.UrlRewriteFilter INFO: destroy called
Exception in thread "Thread-17" com.ui.analytics.ooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.Object.C: Failed to send crash reports or parse response
	at com.ui.analytics.ooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.Object.A.OoOO.super(HttpAnalyticsTransport.java:55)
	at com.ui.analytics.B.oOOO.O0oO.String(CrashReportBatchingClient.java:72)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.UnknownHostException: crash-report-service.svc.ui.com
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:229)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:305)
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:507)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:602)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:373)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:207)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:193)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:246)
	at com.ui.analytics.ooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.Object.A.A.super(HttpSender.java:44)
	at com.ui.analytics.ooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.Object.A.A.Ô00000(HttpSender.java:20)
	at com.ui.analytics.ooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.Object.A.OoOO.super(HttpAnalyticsTransport.java:48)
	... 2 more
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
*** Setting Java memory limit to 1024 ***
*** Setting Java memory minimum to 1024 ***
[custom-init] No custom files found, skipping...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/usr/lib/unifi/lib/tomcat-embed-core-9.0.59.jar) to field java.io.ObjectStreamClass$Caches.localDescs
WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[ls.io-init] done.
```
```

**Comment by ForsakenRei** [comment]
One thing I noticed is my container cannot access internet...from shell? Since ping 8.8.8.8 will return ping not found, I used curl 8.8.8.8 and it returns connection time out, not sure if this is the expecated behavior. The container joined `unifi-controller default` and `bridge` two networks. I also have pi-hole&unbound containers running on the same RPi4.

**Comment by thespad** [comment]
If your controller can't reach the internet it shouldn't be a surprise that it can't send mail either. I just sent myself a test email via Gmail and it seems to be working just fine:


![Image](https://user-images.githubusercontent.com/8425502/230196415-3b755b05-b0e7-45ff-a694-64a4d748be8b.png)

**Comment by ForsakenRei** [comment]
> If your controller can't reach the internet it shouldn't be a surprise that it can't send mail either.

That's my suspect as well. But it works just fine on anything else like managing my devices, update firmware, SSO login and remote access etc.
Any suggestion on where I should start for troubleshooting? Or create a new container and see if it works there...?

**Comment by thespad** [comment]
You need to test that you can actually resolve and reach the SMTP server in question from inside the container. If the tools you need aren't present you can always install them.

**Comment by ForsakenRei** [comment]
> You need to test that you can actually resolve and reach the SMTP server in question from inside the container. If the tools you need aren't present you can always install them.

That's actually where I was stuck. Since I found my container is not "connected" to the internet, I cannot `wget`, `curl` or `apt update`. But I think this is not the expected behavior?
```
root@eda8ada71bd7:/usr/lib/unifi# apt update
Err:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
  Temporary failure resolving 'ports.ubuntu.com'
Err:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
  Temporary failure resolving 'ports.ubuntu.com'
Err:3 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
  Temporary failure resolving 'ports.ubuntu.com'
Reading package lists... Done      
Building dependency tree       
Reading state information... Done
All packages are up to date.
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal/InRelease  Temporary failure resolving 'ports.ubuntu.com'
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal-updates/InRelease  Temporary failure resolving 'ports.ubuntu.com'
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal-security/InRelease  Temporary failure resolving 'ports.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by ForsakenRei** [comment]
It seems to be some problem with that specific container on the RPi4.

I tried other docker containers on the same RPi4 but they can all get access to internet.
Then I tried remove the container after I backup the config, remove the data volumn, then recreate the container. And it just behaved the same, I still have no internet access.

I tried on a different machine with same docker compose file and that controller container has no issue to access the internet.(Didn't try SMTP though)

I'm quite confusing now

**Comment by thespad** [comment]
There's nothing "special" about the Unifi Controller container, it uses the same base image as any of our other Ubuntu containers, so it shouldn't have different network behaviour to any other similar container on the same docker network.

**Comment by ForsakenRei** [comment]
> Are you specifically using the docker default `bridge` network for the controller, as that is a legacy network and has a number of odd quirks that can cause weird behaviour?

No, I used `unifi-controller_default` network created with the container. But I acutually tried `network_mode: bridge` in my `docker-compose.yml` to force it to join the bridge network but it doesn't work either.

**Comment by ForsakenRei** [comment]
I know it's kinda weird, but it seems all linux based docker container on that RPi4 have difficulties on Internect connection.

I checked all my other containers(Debian, Alpine) and it seems they are fine, but unifi-controller(Ubuntu 20.04) and speedtest-tracker and rustdesk(Ubuntu 22.04) all have trouble to connect to Internet within container. Sounds like something wrong with my environment then. I will need spend more time digging it but currently probably migrate Unifi-controller to another machine is the better choice, and thanks for all the help.
