### ISSUE TITLE
[BUG] Spanish language does not apply in docker

### ISSUE THREAD

**Issue by JuanRodenas** [linuxserver/docker-unifi-controller#208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Spanish language does not apply in docker

### Expected Behavior

It is requested that once you change the language to Spanish it is applied in the system.

### Steps To Reproduce

- docker compose up -d
- System/Language
- Change language to Spanish
- Once the changes have been applied, it is still in English

### Environment

```markdown
- OS:Linux Raspi 6.1.19-v8+ #1637 SMP PREEMPT Tue Mar 14 11:11:47 GMT 2023 aarch64 GNU/Linux
I have also tried with x64 and the error persists.
```

### CPU architecture

arm64

### Docker creation

```bash
I have applied as indicated in the blog
```

### Container logs

```bash
unifi-controller  | [migrations] started
unifi-controller  | [migrations] no migrations found
unifi-controller  | ───────────────────────────────────────
unifi-controller  | 
unifi-controller  |       ██╗     ███████╗██╗ ██████╗ 
unifi-controller  |       ██║     ██╔════╝██║██╔═══██╗
unifi-controller  |       ██║     ███████╗██║██║   ██║
unifi-controller  |       ██║     ╚════██║██║██║   ██║
unifi-controller  |       ███████╗███████║██║╚██████╔╝
unifi-controller  |       ╚══════╝╚══════╝╚═╝ ╚═════╝ 
unifi-controller  | 
unifi-controller  |    Brought to you by linuxserver.io
unifi-controller  | ───────────────────────────────────────
unifi-controller  | 
unifi-controller  | To support LSIO projects visit:
unifi-controller  | https://www.linuxserver.io/donate/
unifi-controller  | 
unifi-controller  | ───────────────────────────────────────
unifi-controller  | GID/UID
unifi-controller  | ───────────────────────────────────────
unifi-controller  | 
unifi-controller  | User UID:    1000
unifi-controller  | User GID:    1000
unifi-controller  | ───────────────────────────────────────
unifi-controller  | 
unifi-controller  | *** Setting Java memory limit to 1024 ***
unifi-controller  | *** Setting Java memory minimum to 1024 ***
unifi-controller  | [custom-init] No custom files found, skipping...
unifi-controller  | WARNING: An illegal reflective access operation has occurred
unifi-controller  | WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/usr/lib/unifi/lib/tomcat-embed-core-9.0.59.jar) to field java.io.ObjectStreamClass$Caches.localDescs
unifi-controller  | WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
unifi-controller  | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
unifi-controller  | WARNING: All illegal access operations will be denied in a future release
unifi-controller  | [ls.io-init] done.
unifi-controller  | org.tuckey.web.filters.urlrewrite.UrlRewriteFilter INFO: destroy called
unifi-controller  | Exception in thread "Thread-10" java.lang.IllegalStateException: BeanFactory not initialized or already closed - call 'refresh' before accessing beans via the ApplicationContext
unifi-controller  |     at org.springframework.context.support.AbstractRefreshableApplicationContext.getBeanFactory(AbstractRefreshableApplicationContext.java:168)
unifi-controller  |     at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1172)
unifi-controller  |     at com.ubnt.service.ooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.Ö00000(Unknown Source)
unifi-controller  |     at com.ubnt.ace.Launcher.Ó00000(Unknown Source)
unifi-controller  |     at java.base/java.lang.Thread.run(Thread.java:829)
unifi-controller  | WARNING: An illegal reflective access operation has occurred
unifi-controller  | WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/usr/lib/unifi/lib/tomcat-embed-core-9.0.59.jar) to field java.io.ObjectStreamClass$Caches.localDescs
unifi-controller  | WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
unifi-controller  | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
unifi-controller  | WARNING: All illegal access operations will be denied in a future release
```

**Comment by thespad** [comment]
I can replicate the issue but I can't find anything to suggest *why* it won't change the UI language. There aren't any errors logged and there doesn't appear to be anything documented to suggest that there are extra dependencies required to support additional languages. I've even tried installing the Spanish language packs for the OS (`language-pack-es` & `wspanish`) but it doesn't seem to make a difference.
