### ISSUE TITLE
Http 404 on UI on Fresh installation

### ISSUE THREAD

**Issue by mangusbrother** [linuxserver/docker-unifi-controller#229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to access https://localhost:8443 or http://localhost:8080 I am getting a 404 screen

### Expected Behavior

I am able to access the UI

### Steps To Reproduce

Create a fresh environment and try to access the web UI

### Environment

```markdown
- OS: Windows
- How docker service was installed: Docker Desktop, backed by WSL
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "3.8"
services:
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_USER=unifi
      - MONGO_PASS=unifiPass
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      - ./volumes/unifi:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - unifi-db

  unifi-db:
    image: docker.io/mongo:4.4
    container_name: unifi-db
    volumes:
      - /volumes/mongo/data:/data/db
      - /volumes/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: unless-stopped
```

### Container logs

```bash
2023-10-14 02:08:39 [migrations] started
2023-10-14 02:08:39 [migrations] no migrations found
2023-10-14 02:08:39 ───────────────────────────────────────
2023-10-14 02:08:39 
2023-10-14 02:08:39       ██╗     ███████╗██╗ ██████╗ 
2023-10-14 02:08:39       ██║     ██╔════╝██║██╔═══██╗
2023-10-14 02:08:39       ██║     ███████╗██║██║   ██║
2023-10-14 02:08:39       ██║     ╚════██║██║██║   ██║
2023-10-14 02:08:39       ███████╗███████║██║╚██████╔╝
2023-10-14 02:08:39       ╚══════╝╚══════╝╚═╝ ╚═════╝ 
2023-10-14 02:08:39 
2023-10-14 02:08:39    Brought to you by linuxserver.io
2023-10-14 02:08:39 ───────────────────────────────────────
2023-10-14 02:08:39 
2023-10-14 02:08:39 To support LSIO projects visit:
2023-10-14 02:08:39 https://www.linuxserver.io/donate/
2023-10-14 02:08:39 
2023-10-14 02:08:39 ───────────────────────────────────────
2023-10-14 02:08:39 GID/UID
2023-10-14 02:08:39 ───────────────────────────────────────
2023-10-14 02:08:39 
2023-10-14 02:08:39 User UID:    1000
2023-10-14 02:08:39 User GID:    1000
2023-10-14 02:08:39 ───────────────────────────────────────
2023-10-14 02:08:39 
2023-10-14 02:08:39 [custom-init] No custom files found, skipping...
2023-10-14 02:08:43 09:08:43,079 |-INFO in ch.qos.logback.access.tomcat.LogbackValve[null] - Could NOT configuration file [/usr/lib/unifi/logback-access.xml] using property "catalina.base"
2023-10-14 02:08:43 09:08:43,079 |-INFO in ch.qos.logback.access.tomcat.LogbackValve[null] - Could NOT configuration file [/usr/lib/unifi/logback-access.xml] using property "catalina.home"
2023-10-14 02:08:43 09:08:43,079 |-INFO in ch.qos.logback.access.tomcat.LogbackValve[null] - Found [logback-access.xml] as a resource.
2023-10-14 02:08:43 09:08:43,080 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@d48673 - URL [jar:file:/usr/lib/unifi/lib/ace.jar!/logback-access.xml] is not of type file
2023-10-14 02:08:43 09:08:43,094 |-INFO in ch.qos.logback.access.joran.action.ConfigurationAction - debug attribute not set
2023-10-14 02:08:43 09:08:43,094 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
2023-10-14 02:08:43 09:08:43,094 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [access_log]
2023-10-14 02:08:43 09:08:43,096 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@548d5ed3 - No compression will be used
2023-10-14 02:08:43 09:08:43,097 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.access.PatternLayoutEncoder] for [encoder] property
2023-10-14 02:08:43 09:08:43,104 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[access_log] - Active log file name: logs/access.log
2023-10-14 02:08:43 09:08:43,104 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[access_log] - File property is set to [logs/access.log]
2023-10-14 02:08:43 09:08:43,104 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [access_log] to ch.qos.logback.access.tomcat.LogbackValve[null]
2023-10-14 02:08:43 09:08:43,104 |-INFO in ch.qos.logback.access.joran.action.ConfigurationAction - End of configuration.
2023-10-14 02:08:43 09:08:43,105 |-INFO in ch.qos.logback.access.joran.JoranConfigurator@21c7208d - Registering current configuration as safe fallback point
2023-10-14 02:08:43 09:08:43,105 |-INFO in ch.qos.logback.access.tomcat.LogbackValve[null] - Done configuring
```
```

**Comment by bassings** [comment]
I am getting something similar on a clean install:
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

[custom-init] No custom files found, skipping...
no crontab for abc
no crontab for root
Exception in thread "launcher" java.lang.NullPointerException: Web context failed to initialize
        at java.base/java.util.Objects.requireNonNull(Objects.java:235)
        at com.ubnt.net.ooOO.ÖÒ0000(Unknown Source)
        at com.ubnt.net.ooOO.Òo0000(Unknown Source)
        at com.ubnt.service.C.classObject(Unknown Source)
        at com.ubnt.ace.Launcher.Object(Unknown Source)
        at com.ubnt.ace.Launcher.main(Unknown Source)

**Comment by domb84** [comment]
> I am getting something similar on a clean install: [migrations] started [migrations] no migrations found usermod: no changes ───────────────────────────────────────
> 
> ```
>   ██╗     ███████╗██╗ ██████╗ 
>   ██║     ██╔════╝██║██╔═══██╗
>   ██║     ███████╗██║██║   ██║
>   ██║     ╚════██║██║██║   ██║
>   ███████╗███████║██║╚██████╔╝
>   ╚══════╝╚══════╝╚═╝ ╚═════╝ 
> ```
> 
> Brought to you by linuxserver.io ───────────────────────────────────────
> 
> To support LSIO projects visit: https://www.linuxserver.io/donate/
> 
> ─────────────────────────────────────── GID/UID ───────────────────────────────────────
> 
> User UID: 1000 User GID: 1000 ───────────────────────────────────────
> 
> [custom-init] No custom files found, skipping... no crontab for abc no crontab for root Exception in thread "launcher" java.lang.NullPointerException: Web context failed to initialize at java.base/java.util.Objects.requireNonNull(Objects.java:235) at com.ubnt.net.ooOO.ÖÒ0000(Unknown Source) at com.ubnt.net.ooOO.Òo0000(Unknown Source) at com.ubnt.service.C.classObject(Unknown Source) at com.ubnt.ace.Launcher.Object(Unknown Source) at com.ubnt.ace.Launcher.main(Unknown Source)

Get this same issue running on an rpi4. Seems to start populating the mongodb then fails with this exception.

**Comment by drizuid** [comment]
>     image: lscr.io/linuxserver/unifi-network-application:latest

you've posted under unifi-controller but are not using unifi-controller. That said, we do not test or support WSL2. While it should work, it's not something we will spend time debugging. First startup can take a while, however.
