### ISSUE TITLE
Unable to upload Logo or Background image for Guest Portal

### ISSUE THREAD

**Issue by nstayte** [linuxserver/docker-unifi-controller#66]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
I should be able to upload Custom Logo and Background images for portal customization. 
I am not sure if this a container issue or an issue with the Unifi software. I am happy to log an issue with Unifi if this is the case.

## Current Behavior
When choosing either a custom logo or background image I get the following error: "There was an error uploading file. Please try again later."

## Steps to Reproduce

1. Enable the guest portal
2. Change either the custom logo or background image under Portal Customization (png or jpg)
3. Click apply changes
4. A notification should appear with the error message

## Environment
**OS:** Unraid 6.8.3
**CPU architecture:** x86_64
**How docker service was installed:** Community Applications

## Command used to create docker container (run/create/compose/screenshot)
Using standard values provided by Community Applications
Using the latest tag, fresh install.

## Docker logs

```
<webapi-790> ERROR [UploadServlet] - Servlet.service() for servlet [UploadServlet] in context with path [] threw exception [Servlet execution threw an exception] with root cause
java.lang.NoClassDefFoundError: Could not initialize class javax.imageio.ImageTypeSpecifier
	at com.sun.imageio.plugins.png.PNGImageReader.getImageTypes(PNGImageReader.java:1531) ~[?:1.8.0_275]
	at com.sun.imageio.plugins.png.PNGImageReader.readImage(PNGImageReader.java:1318) ~[?:1.8.0_275]
	at com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1614) ~[?:1.8.0_275]
	at javax.imageio.ImageIO.read(ImageIO.java:1462) ~[?:1.8.0_275]
	at javax.imageio.ImageIO.read(ImageIO.java:1309) ~[?:1.8.0_275]
	at com.ubnt.ace.view.UploadServlet.service(Unknown Source) ~[ace.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.56.jar:8.5.56]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.56.jar:8.5.56]
	at com.ubnt.ace.view.AuthFilter.doFilter(Unknown Source) ~[ace.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543) [tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615) [tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818) [tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1627) [tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.56.jar:8.5.56]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.56.jar:8.5.56]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
```

**Comment by Rhahkeem** [comment]
having in the same issue actually

**Comment by davidkuhta** [comment]
Same issue

**Comment by drizuid** [comment]
I am unable to reproduce the issue; OP did not provide the docker run output to allow us to match their deployment. It's likely permissions, but impossible to tell due to lack of info.
